### ISSUE TITLE
Update that Changed URL fields from CharField to TextField leads to issue on MS SQLServer

### ISSUE THREAD

**Issue by jdkizer9** [soynatan/django-easy-audit#55] opened 2018-03-29 16:34 UTC
Running migration 0009_auto_20180314_2225 causes the following error:

```
Running migrations:
  Applying easyaudit.0009_auto_20180314_2225...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/sql_server/pyodbc/base.py", line 520, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Column 'url' in table 'easyaudit_requestevent' is of a type that is invalid for use as a key column in an index. (1919) (SQLExecDirectW)")
```

**Comment by imran-iq** [comment] 2018-04-17 19:51
Same issue with mysql

```
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'url' used in key specification without a key length")
```

**Comment by jheld** [comment] 2018-04-17 20:26
@imran-iq thanks for noting this, too.

django docs regarding text (really char) field:

https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.CharField.max_length


@jdkizer9 I haven't looked into this yet. Have you learned anything further?

**Comment by rnegron** [comment] 2018-10-02 15:00
The issue is the following snippet in the file `easyaudit/migrations/0009_auto_20180314_2225.py`: 

```python
migrations.AlterField(
            model_name='requestevent',
            name='url',
            field=models.TextField(db_index=True),
        ),
```
Running this migration gives the following warning: 

_"easyaudit.RequestEvent.url: (fields.W162) MySQL does not support a database index on longtext columns. HINT: An index won't be created. Silence this warning if you don't care about it."_

Possible quick fixes: 
1. Change `TextField` to `CharField` with `max_length` property and keep the `db_index`.
2. Remove the `db_index` from the `TextField`.

See: https://code.djangoproject.com/ticket/27859 and corresponding commit https://github.com/django/django/commit/538bf43458a147b7edeb7118c9f325c3f59ff6fb

Notes: Running on Django 2.1 and MySQL 5.6.10.

**Comment by UmSenhorQualquer** [comment] 2019-04-04 12:57
I got the same error with MariaDB. 
I dropped the index from the url field manually and it worked.

The issue is that in the migration 0006 the url field is created with index and then on the 0009 migration the field is updated to a text type which is not allowed without the passing the field length.

**Comment by jheld** [comment] 2019-04-04 21:26
Shall we include an update to the migration which includes maybe 1000 as length?

**Comment by UmSenhorQualquer** [comment] 2019-04-04 23:30
2000 of length is the maximum size of an url on Chrome:
https://www.quora.com/What-is-the-maximum-length-of-a-URL-in-different-browsers

**Comment by jheld** [comment] 2019-04-04 23:34
So turns out I made a mistake with the PR that made this happen. A change was needed, but I did it wrong. Query params are stored separately. We may need to include a max length on query params, and leave url as max length 254.

@soynatan ?

**Comment by soynatan** [comment] 2019-04-08 12:54
So, if we add a `max_length` to url, which is now a TextField, will it allow us to keep the index. Otherwise, we could change url to `CharField` with `max_length` 254 and keep the `db_index`.

> We may need to include a max length on query params

[According to doc](https://docs.djangoproject.com/en/dev/ref/models/fields/#textfield), `max_length` on `TextField` is not enforced at database level, only in the Textarea widget, when using forms. So is it necessary?

**Comment by jwerardi** [comment] 2019-04-15 15:49
any update on a resolution? I've just been ignoring the failed migration because this plugin is worth it, but I would like to clean stuff up eventually.

**Comment by soynatan** [comment] 2019-04-22 10:58
Honestly, I've been a little out of the loop lately, so I'm not sure if my proposal is the best way to go. I thought of changing url field to `CharField` with `max_length` of 254, keeping the `db_index`.

But I may be overlooking something that was already discussed?

**Comment by jheld** [comment] 2019-05-22 23:43
@soynatan do you have bandwidth for this? I can try otherwise.

**Comment by pmi123** [comment] 2019-07-24 15:43
I just installed the most recent version of django-easy-audit and made the above change (jheld). I now get this warning - 

WARNINGS:
easyaudit.RequestEvent.url: (fields.W162) MySQL does not support a database index on longtext columns.
	HINT: An index won't be created. Silence this warning if you don't care about it.

Should the db_index be removed from the CharField?

**Comment by jheld** [comment] 2019-07-24 16:08
unfortunately it was because I changed it to a textfield and this happened. Please see PR #100 which I hope will solve this issue.

**Comment by jheld** [comment] 2019-08-11 16:32
@pmi123 please checkout #100 ; I may issue a new beta version of the project with this change in the next week or so, but the code is available on the branch if you are available to test it.

**Comment by ahoneycutt** [comment] 2019-09-18 21:11
Is there any update on this? I would like to use this package but the production instances that would be using this will exhibit this issue.

**Comment by jheld** [comment] 2019-09-18 21:32
@ahoneycutt would you be willing to try a beta release? My confidence level is high, but I have yet to run the migration through, and I use MySQL. #100

**Comment by ahoneycutt** [comment] 2019-09-18 21:37
@jheld I'd be happy to run some user testing and run my application's test suite with the migrations from your beta release. I can see if we can push it to staging for a while and see if anything breaks.

**Comment by ahoneycutt** [comment] 2019-09-18 21:58
@jheld I'm testing with the merged version and will let you know how it goes.

**Comment by ahoneycutt** [comment] 2019-09-18 22:31
@jheld Ran against backend testing ~1800 tests without incident.

**Comment by jheld** [comment] 2019-09-20 20:01
@ahoneycutt can you put this comment on the PR, too? make it easier to track the successful tests output.

Yeah I think if the migration went through we're doing pretty well. I can mark this as an `rc` release if that makes people feel better, too. And then after things look good, go GA.

**Comment by ahoneycutt** [comment] 2019-09-21 12:31
:+1: Thanks @jheld

**Comment by jheld** [comment] 2019-10-02 00:50
Release 1.1.1rc1 is now available on PyPI! It includes just the fix for this. If feedback is good, it'll become 1.1.1

**Comment by ahoneycutt** [comment] 2019-10-02 03:00
@jheld That's fantastic. Much appreciated.

**Comment by jheld** [comment] 2019-10-18 15:03
My project is using 1.1.1rc1 and so far no issues (did migrate, did a small test on request event), no issues so far.

There might be a postgres issue #105 but just one reporter so far. If it becomes a problem (or even just the one time), I'm willing to work with anyone directly to find a way for them forward. Migrations (IMO) can be hard to get right for all db, and fixes like the one I had to unbreak made it worse!

Closing this, please re-open (or new issue) if problems arise from 1.1.1(rc1).

**Closed by jheld** 2019-10-18 15:03 UTC
Labels: bug, database

**Comment by jheld** [comment] 2019-10-24 01:12
1.1.1 has now been released. Please open any resulting issues you find, though we're hoping this release is a good path forward for everyone. We are now starting to merge new feature requests!
