### ISSUE TITLE
Add ability to filter sensitive fields from being logged.

### ISSUE THREAD

**Issue by gghildyal** [soynatan/django-easy-audit#113] opened 2019-10-25 15:03 UTC
I want to filter out secrets that are stored as encrypted fields in the database, but are non-encrypted when read out. This means that they are also audited as plain text.

One way to filter it would be in the callback, but that's currently not possible because the object_json is a string and passed as value, so the callback cannot remove the fields or obfuscate them.

**Comment by jheld** [comment] 2020-08-09 13:27
Seems like a duplicate of #92

**Closed by jheld** 2020-08-09 13:27 UTC
