### ISSUE TITLE
Exception when creating users in v1.1 (does not happen in v1.0)

### ISSUE THREAD

**Issue by ishirav** [soynatan/django-easy-audit#88] opened 2019-05-20 12:27 UTC
Since upgrading to v1.1, when trying to create a User instance we encounter an exception:

    > User.objects.create_user(username='test1')

    2019-05-20 12:15:24,074 [ERROR] MainThread model_signals easy audit had a pre-save exception.
    Traceback (most recent call last):
      File "/home/itais/workspace/infinidat/flux/eggs/django_easy_audit-1.1-py3.7.egg/easyaudit/signals/model_signals.py", line 56, in pre_save
        object_json_repr = serializers.serialize("json", [instance])
      File "/home/itais/workspace/infinidat/flux/eggs/Django-2.0.2-py3.7.egg/django/core/serializers/__init__.py", line 128, in serialize
        s.serialize(queryset, **options)
      File "/home/itais/workspace/infinidat/flux/eggs/Django-2.0.2-py3.7.egg/django/core/serializers/base.py", line 96, in serialize
        self.handle_m2m_field(obj, field)
      File "/home/itais/workspace/infinidat/flux/eggs/Django-2.0.2-py3.7.egg/django/core/serializers/python.py", line 72, in handle_m2m_field
        m2m_value(related) for related in getattr(obj, field.name).iterator()
      File "/home/itais/workspace/infinidat/flux/eggs/Django-2.0.2-py3.7.egg/django/db/models/fields/related_descriptors.py", line 498, in __get__
        return self.related_manager_cls(instance)
      File "/home/itais/workspace/infinidat/flux/eggs/Django-2.0.2-py3.7.egg/django/db/models/fields/related_descriptors.py", line 795, in __init__
        (instance, self.pk_field_names[self.source_field_name]))
    ValueError: "<User: >" needs to have a value for field "id" before this many-to-many relationship can be used.

Our settings:

    DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False
    DJANGO_EASY_AUDIT_ADMIN_SHOW_REQUEST_EVENTS = False
    DJANGO_EASY_AUDIT_REGISTERED_CLASSES = [
        'auth.User',
        'users.UserInfo',
    ]

**Comment by jheld** [comment] 2019-05-22 23:42
I'm surprised that you were not seeing this before. What was added in 1.1 was an exception handling logging which you're seeing there. Before 1.0 this would have crashed the signal handler invocation (it was an uncaught exception).

Good news is its just a log. We'd like to actually fix it, but it would require changing how the changed fields field gets generated.

**Comment by dgrant** [comment] 2019-07-28 08:07
I'm seeing this as well.

**Comment by jheld** [comment] 2019-08-11 16:28
Closing as this is not technically a bug -- noisy, but not a bug. Any changes around the logger itself should be opened as a new issue or PR. Thank you!

Changes to how the changed fields are generated should likewise be its own issue or PR.

**Closed by jheld** 2019-08-11 16:28 UTC
Labels: wontfix
